### ISSUE TITLE
Filtering Text Algorithm 

### ISSUE THREAD

**Issue by qchenax** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#12]
In the filtering data Algorithm, we need to "filter data using the text label", what does this algorithm actually do on the data?

**Comment by hkpeterpeter** [comment]
The following is one of the use cases:

The dataset may have 5 columns. One column may be used to store text data (e.g. Female, Male). We may be interested to filter out Male data, and only use Female data rows to plot the chart.
