### ISSUE TITLE
What does it mean - "applying transformation" in feature #3 ?

### ISSUE THREAD

**Issue by tanmaygoel** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#13]
Your application should be able to handle multiple datasets and charts. A user interface
should be provided to allow user selecting a dataset, applying transformation, and creating
charts. 

Can you explain this feature in more clear language.

**Comment by hkpeterpeter** [comment]
The base code don't have any user interface to support multiple datasets and charts. Your team needs to implement them.
