### ISSUE TITLE
How do Filtering Algorithms perform?

### ISSUE THREAD

**Issue by qchenax** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#14]
It seems all the filtering and transformation are applied on a specific data column, right? When filtering are we gonna delete all the rows which does not meet the filter criteria?

**Comment by hkpeterpeter** [comment]
Pick filtering text as an example, the following is one of the use cases:

The dataset may have 5 columns. One column may be used to store text data (e.g. Female, Male). We may be interested to filter out Male data, and only use Female data rows to plot the chart.
