### ISSUE TITLE
For importing csv file

### ISSUE THREAD

**Issue by wchoiac** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#16]
Previously, I asked whether we can validate the integer or floating number only for numeric filtering keyword. Now, I want to ask whether we can assume that all the numeric type columns are having integer or floating numbers, just to make sure.

**Comment by hkpeterpeter** [comment]
As mentioned in the grading plan, the datasets are fully managed and prepared by your team. The other team grading your project can’t modify or add any any new dataset.
