### ISSUE TITLE
For pie chart category column

### ISSUE THREAD

**Issue by wchoiac** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#4]
For pie chart, it's mentioned that the user should choose two columns; one for the categories and the other for the relative size.

So, among the rows in the column for the categories, do we assume that each row contains unique category name? (if the chosen column has two string value of "A", just create two separate section for A)

**Comment by hkpeterpeter** [comment]
Yes. It is a reasonable assumption.
