### ISSUE TITLE
For numeric filtering

### ISSUE THREAD

**Issue by wchoiac** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#6]
I'm planning to handle only integer values and floating point(double) values for the keyword of numeric filtering; I'm planning to give alert if the keyword is hexadecimal, not numeric value, etc. Would it be okay?

**Comment by hkpeterpeter** [comment]
Filter data using various comparison operators (the complete list of comparison operators: >=, >, ==, !=, <, <=). You can assume that the input filter value is a floating point number / integer. The problem description does not mention about hexadecimal. You can decide to implement that, but as I mentioned, no bonus points will be given for the extra work.
