### ISSUE TITLE
Location for comboboxes in charts

### ISSUE THREAD

**Issue by ddddkim0525** [hkpeterpeter/COMP3111-Spring2018-ProjectBaseCode#7]
For drawing line charts and pie charts, do I put the combo box with the graph, so it redraws the graph every time there is a change in the combo box? Or can I put a combo box in a window before drawing the graph so the user can't change the chart once drawn?

**Comment by hkpeterpeter** [comment]
There is no such UI requirements for that feature. Please pick the best (or the easiest) way of UI interaction by your team.
